# Generated by Django 3.0.4 on 2020-03-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_minuted',
            new_name='time_minutes',
        ),
    ]
